### ISSUE TITLE
cannot call 'codex --help'

### ISSUE THREAD

**Issue by GooBitGitKome** [Gonsix/Code-Agent#1]
I just installed codex and set the environment variable OPEN_API_KEY, then called the command though, it ended up failing. Why was that? 

PC:
python 3.11.6

Error code:
2024-03-08 18:28:29 JST INFO    root_path: 
Traceback (most recent call last):
  File "/Users/pcname/workspace/dev-llm/llm-streamlit/venv/bin/codex", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/pcname/workspace/dev-llm/llm-streamlit/venv/lib/python3.11/site-packages/codex/run.py", line 74, in main
    run()
  File "/Users/pcname/workspace/dev-llm/llm-streamlit/venv/lib/python3.11/site-packages/codex/run.py", line 60, in run
    librarian.start()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...

**Comment by Gonsix** [comment]
@GooBitGitKome 
Thanks for the issues!  But how did you install ? Proper way to install codex command is `pip install code-agent` not `pip install codex`. Are you sure about this?

**Comment by Gonsix** [comment]
After installing the code-agent package on your system or virtual environment, you should be able to use the codex command and its help. Note that if installed in a virtual environment, it can only be used while that environment is active.

**Comment by GooBitGitKome** [comment]
Thank you for the reply. I updated code-agent, and then codex could work properly. Probably, the old package had something causing error? Anyway, thank you.

**Comment by Gonsix** [comment]
Close as You seem to install with wrong command.

**Comment by GooBitGitKome** [comment]
Ah I see, sorry for my mistake. Thank you
